Allow `GameBase.Initialize()` to be run multiple times to restart the game
ppy/osu-stream pull request #26
Opened 2021-08-18 04:34 UTC by Beyley

This is to fix an issue with the ongoing android PR (#24), allowing the game to continue running even if you call `GameBase.Initialize()` while its already running, as this crash seems to be the only issue with that

2021-08-18 18:49 UTC, Trigger-b0y approved these changes

2021-08-20 06:37 UTC, peppy requested changes

2021-08-20 06:37 UTC, peppy commented on osu!stream/Graphics/TextureManager_Load.cs
> +            }
```suggestion
            textureLocations.Clear();
            textureLocations.Add(OsuTexture.play_menu_background, new SpriteSheetTexture("hit", 0, 0, 1385, 210));
            textureLocations.Add(OsuTexture.spinner_background, new SpriteSheetTexture("hit", 0, 212, 1136, 640));
            textureLocations.Add(OsuTexture.cleared, new SpriteSheetTexture("hit", 0, 854, 1024, 654));
            textureLocations.Add(OsuTexture.scorebar_background, new SpriteSheetTexture("hit", 1138, 212, 704, 58));
            textureLocations.Add(OsuTexture.scorebar_colour, new SpriteSheetTexture("hit", 1387, 0, 646, 14));
            textureLocations.Add(OsuTexture.spinner_circle, new SpriteSheetTexture("hit", 1138, 272, 616, 616));
            textureLocations.Add(OsuTexture.countdown_background, new SpriteSheetTexture("hit", 0, 1510, 545, 203));
            textureLocations.Add(OsuTexture.spinner_clear, new SpriteSheetTexture("hit", 1387, 16, 510, 168));
            textureLocations.Add(OsuTexture.countdown_ready, new SpriteSheetTexture("hit", 0, 1715, 422, 90));
            textureLocations.Add(OsuTexture.failed, new SpriteSheetTexture("hit", 0, 1807, 388, 118));
            textureLocations.Add(OsuTexture.spinner_spin, new SpriteSheetTexture("hit", 1026, 890, 382, 170));
            textureLocations.Add(OsuTexture.demo, new SpriteSheetTexture("hit", 547, 1510, 350, 124));
            textureLocations.Add(OsuTexture.stream_changing_up, new SpriteSheetTexture("hit", 1026, 1062, 322, 194));
            textureLocations.Add(OsuTexture.stream_changing_down, new SpriteSheetTexture("hit", 424, 1715, 322, 182));
            textureLocations.Add(OsuTexture.play_menu_continue, new SpriteSheetTexture("hit", 1026, 1258, 316, 152));
            textureLocations.Add(OsuTexture.play_menu_quit, new SpriteSheetTexture("hit", 1410, 890, 316, 152));
            textureLocations.Add(OsuTexture.play_menu_restart, new SpriteSheetTexture("hit", 899, 1510, 316, 152));
            textureLocations.Add(OsuTexture.countdown_go, new SpriteSheetTexture("hit", 1350, 1062, 314, 144));
            textureLocations.Add(OsuTexture.sliderfollowcircle, new SpriteSheetTexture("hit", 1756, 272, 256, 256));
            textureLocations.Add(OsuTexture.stream_changing_arrow, new SpriteSheetTexture("hit", 1756, 530, 200, 266));
            textureLocations.Add(OsuTexture.hit300g, new SpriteSheetTexture("hit", 748, 1664, 190, 190));
            textureLocations.Add(OsuTexture.hit300k, new SpriteSheetTexture("hit", 1756, 798, 190, 190));
            textureLocations.Add(OsuTexture.hit300, new SpriteSheetTexture("hit", 1350, 1208, 188, 190));
            textureLocations.Add(OsuTexture.hit100, new SpriteSheetTexture("hit", 940, 1664, 180, 180));
            textureLocations.Add(OsuTexture.hit100k, new SpriteSheetTexture("hit", 1217, 1412, 180, 180));
            textureLocations.Add(OsuTexture.holdoverlay, new SpriteSheetTexture("hit", 748, 1856, 160, 160));
            textureLocations.Add(OsuTexture.countdown_2, new SpriteSheetTexture("hit", 1666, 1044, 158, 142));
            textureLocations.Add(OsuTexture.countdown_3, new SpriteSheetTexture("hit", 1540, 1208, 158, 138));
            textureLocations.Add(OsuTexture.hit0, new SpriteSheetTexture("hit", 910, 1856, 152, 148));
            textureLocations.Add(OsuTexture.hit50, new SpriteSheetTexture("hit", 1899, 16, 132, 132));
            textureLocations.Add(OsuTexture.tracks, new SpriteSheetTexture("hit", 1387, 186, 132, 16));
            textureLocations.Add(OsuTexture.hitcircle0, new SpriteSheetTexture("hit", 390, 1899, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle1, new SpriteSheetTexture("hit", 520, 1899, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle2, new SpriteSheetTexture("hit", 1122, 1664, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle3, new SpriteSheetTexture("hit", 1399, 1400, 128, 128));
            textureLocations.Add(OsuTexture.holdactive, new SpriteSheetTexture("hit", 1899, 150, 118, 118));
            textureLocations.Add(OsuTexture.holdinactive, new SpriteSheetTexture("hit", 1826, 990, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_0, new SpriteSheetTexture("hit", 1540, 1348, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_1, new SpriteSheetTexture("hit", 1700, 1188, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_2, new SpriteSheetTexture("hit", 1122, 1794, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_3, new SpriteSheetTexture("hit", 1252, 1594, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_4, new SpriteSheetTexture("hit", 1399, 1530, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_5, new SpriteSheetTexture("hit", 1826, 1110, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_6, new SpriteSheetTexture("hit", 1252, 1714, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_7, new SpriteSheetTexture("hit", 1700, 1308, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_8, new SpriteSheetTexture("hit", 1529, 1468, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_9, new SpriteSheetTexture("hit", 1064, 1914, 118, 118));
            textureLocations.Add(OsuTexture.sliderballoverlay, new SpriteSheetTexture("hit", 0, 1927, 118, 74));
            textureLocations.Add(OsuTexture.countdown_1, new SpriteSheetTexture("hit", 1958, 530, 86, 134));
            textureLocations.Add(OsuTexture.scorebar_marker_hit, new SpriteSheetTexture("hit", 120, 1927, 78, 78));
            textureLocations.Add(OsuTexture.sliderarrow, new SpriteSheetTexture("hit", 200, 1927, 78, 58));
            textureLocations.Add(OsuTexture.finger_outer, new SpriteSheetTexture("hit", 547, 1636, 74, 74));
            textureLocations.Add(OsuTexture.score_percent, new SpriteSheetTexture("hit", 280, 1927, 60, 48));
            textureLocations.Add(OsuTexture.finger_inner, new SpriteSheetTexture("hit", 623, 1636, 58, 58));
            textureLocations.Add(OsuTexture.default_0, new SpriteSheetTexture("hit", 200, 1987, 54, 40));
            textureLocations.Add(OsuTexture.default_2, new SpriteSheetTexture("hit", 256, 1987, 54, 40));
            textureLocations.Add(OsuTexture.default_3, new SpriteSheetTexture("hit", 312, 1977, 54, 40));
            textureLocations.Add(OsuTexture.default_4, new SpriteSheetTexture("hit", 683, 1636, 54, 40));
            textureLocations.Add(OsuTexture.default_5, new SpriteSheetTexture("hit", 1026, 1412, 54, 40));
            textureLocations.Add(OsuTexture.default_6, new SpriteSheetTexture("hit", 1026, 1454, 54, 40));
            textureLocations.Add(OsuTexture.default_7, new SpriteSheetTexture("hit", 1082, 1412, 54, 40));
            textureLocations.Add(OsuTexture.default_8, new SpriteSheetTexture("hit", 1082, 1454, 54, 40));
            textureLocations.Add(OsuTexture.default_9, new SpriteSheetTexture("hit", 650, 1899, 54, 40));
            textureLocations.Add(OsuTexture.pausebutton, new SpriteSheetTexture("hit", 1844, 186, 48, 48));
            textureLocations.Add(OsuTexture.score_0, new SpriteSheetTexture("hit", 342, 1927, 42, 48));
            textureLocations.Add(OsuTexture.mouse_burst, new SpriteSheetTexture("hit", 1138, 1412, 38, 38));
            textureLocations.Add(OsuTexture.score_6, new SpriteSheetTexture("hit", 1138, 1452, 36, 48));
            textureLocations.Add(OsuTexture.score_8, new SpriteSheetTexture("hit", 1178, 1412, 36, 48));
            textureLocations.Add(OsuTexture.score_9, new SpriteSheetTexture("hit", 650, 1941, 36, 48));
            textureLocations.Add(OsuTexture.score_x, new SpriteSheetTexture("hit", 706, 1899, 36, 48));
            textureLocations.Add(OsuTexture.score_2, new SpriteSheetTexture("hit", 1958, 666, 34, 48));
            textureLocations.Add(OsuTexture.score_3, new SpriteSheetTexture("hit", 688, 1949, 34, 48));
            textureLocations.Add(OsuTexture.score_4, new SpriteSheetTexture("hit", 19 [...]

2021-08-20 06:37 UTC, peppy commented on osu!stream/Graphics/TextureManager_Load.cs
> +            }
```suggestion
            textureLocations.Clear();
            textureLocations.Add(OsuTexture.play_menu_background, new SpriteSheetTexture("hit", 0, 0, 1385, 210));
            textureLocations.Add(OsuTexture.spinner_background, new SpriteSheetTexture("hit", 0, 212, 1136, 640));
            textureLocations.Add(OsuTexture.cleared, new SpriteSheetTexture("hit", 0, 854, 1024, 654));
            textureLocations.Add(OsuTexture.scorebar_background, new SpriteSheetTexture("hit", 1138, 212, 704, 58));
            textureLocations.Add(OsuTexture.scorebar_colour, new SpriteSheetTexture("hit", 1387, 0, 646, 14));
            textureLocations.Add(OsuTexture.spinner_circle, new SpriteSheetTexture("hit", 1138, 272, 616, 616));
            textureLocations.Add(OsuTexture.countdown_background, new SpriteSheetTexture("hit", 0, 1510, 545, 203));
            textureLocations.Add(OsuTexture.spinner_clear, new SpriteSheetTexture("hit", 1387, 16, 510, 168));
            textureLocations.Add(OsuTexture.countdown_ready, new SpriteSheetTexture("hit", 0, 1715, 422, 90));
            textureLocations.Add(OsuTexture.failed, new SpriteSheetTexture("hit", 0, 1807, 388, 118));
            textureLocations.Add(OsuTexture.spinner_spin, new SpriteSheetTexture("hit", 1026, 890, 382, 170));
            textureLocations.Add(OsuTexture.demo, new SpriteSheetTexture("hit", 547, 1510, 350, 124));
            textureLocations.Add(OsuTexture.stream_changing_up, new SpriteSheetTexture("hit", 1026, 1062, 322, 194));
            textureLocations.Add(OsuTexture.stream_changing_down, new SpriteSheetTexture("hit", 424, 1715, 322, 182));
            textureLocations.Add(OsuTexture.play_menu_continue, new SpriteSheetTexture("hit", 1026, 1258, 316, 152));
            textureLocations.Add(OsuTexture.play_menu_quit, new SpriteSheetTexture("hit", 1410, 890, 316, 152));
            textureLocations.Add(OsuTexture.play_menu_restart, new SpriteSheetTexture("hit", 899, 1510, 316, 152));
            textureLocations.Add(OsuTexture.countdown_go, new SpriteSheetTexture("hit", 1350, 1062, 314, 144));
            textureLocations.Add(OsuTexture.sliderfollowcircle, new SpriteSheetTexture("hit", 1756, 272, 256, 256));
            textureLocations.Add(OsuTexture.stream_changing_arrow, new SpriteSheetTexture("hit", 1756, 530, 200, 266));
            textureLocations.Add(OsuTexture.hit300g, new SpriteSheetTexture("hit", 748, 1664, 190, 190));
            textureLocations.Add(OsuTexture.hit300k, new SpriteSheetTexture("hit", 1756, 798, 190, 190));
            textureLocations.Add(OsuTexture.hit300, new SpriteSheetTexture("hit", 1350, 1208, 188, 190));
            textureLocations.Add(OsuTexture.hit100, new SpriteSheetTexture("hit", 940, 1664, 180, 180));
            textureLocations.Add(OsuTexture.hit100k, new SpriteSheetTexture("hit", 1217, 1412, 180, 180));
            textureLocations.Add(OsuTexture.holdoverlay, new SpriteSheetTexture("hit", 748, 1856, 160, 160));
            textureLocations.Add(OsuTexture.countdown_2, new SpriteSheetTexture("hit", 1666, 1044, 158, 142));
            textureLocations.Add(OsuTexture.countdown_3, new SpriteSheetTexture("hit", 1540, 1208, 158, 138));
            textureLocations.Add(OsuTexture.hit0, new SpriteSheetTexture("hit", 910, 1856, 152, 148));
            textureLocations.Add(OsuTexture.hit50, new SpriteSheetTexture("hit", 1899, 16, 132, 132));
            textureLocations.Add(OsuTexture.tracks, new SpriteSheetTexture("hit", 1387, 186, 132, 16));
            textureLocations.Add(OsuTexture.hitcircle0, new SpriteSheetTexture("hit", 390, 1899, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle1, new SpriteSheetTexture("hit", 520, 1899, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle2, new SpriteSheetTexture("hit", 1122, 1664, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle3, new SpriteSheetTexture("hit", 1399, 1400, 128, 128));
            textureLocations.Add(OsuTexture.holdactive, new SpriteSheetTexture("hit", 1899, 150, 118, 118));
            textureLocations.Add(OsuTexture.holdinactive, new SpriteSheetTexture("hit", 1826, 990, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_0, new SpriteSheetTexture("hit", 1540, 1348, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_1, new SpriteSheetTexture("hit", 1700, 1188, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_2, new SpriteSheetTexture("hit", 1122, 1794, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_3, new SpriteSheetTexture("hit", 1252, 1594, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_4, new SpriteSheetTexture("hit", 1399, 1530, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_5, new SpriteSheetTexture("hit", 1826, 1110, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_6, new SpriteSheetTexture("hit", 1252, 1714, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_7, new SpriteSheetTexture("hit", 1700, 1308, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_8, new SpriteSheetTexture("hit", 1529, 1468, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_9, new SpriteSheetTexture("hit", 1064, 1914, 118, 118));
            textureLocations.Add(OsuTexture.sliderballoverlay, new SpriteSheetTexture("hit", 0, 1927, 118, 74));
            textureLocations.Add(OsuTexture.countdown_1, new SpriteSheetTexture("hit", 1958, 530, 86, 134));
            textureLocations.Add(OsuTexture.scorebar_marker_hit, new SpriteSheetTexture("hit", 120, 1927, 78, 78));
            textureLocations.Add(OsuTexture.sliderarrow, new SpriteSheetTexture("hit", 200, 1927, 78, 58));
            textureLocations.Add(OsuTexture.finger_outer, new SpriteSheetTexture("hit", 547, 1636, 74, 74));
            textureLocations.Add(OsuTexture.score_percent, new SpriteSheetTexture("hit", 280, 1927, 60, 48));
            textureLocations.Add(OsuTexture.finger_inner, new SpriteSheetTexture("hit", 623, 1636, 58, 58));
            textureLocations.Add(OsuTexture.default_0, new SpriteSheetTexture("hit", 200, 1987, 54, 40));
            textureLocations.Add(OsuTexture.default_2, new SpriteSheetTexture("hit", 256, 1987, 54, 40));
            textureLocations.Add(OsuTexture.default_3, new SpriteSheetTexture("hit", 312, 1977, 54, 40));
            textureLocations.Add(OsuTexture.default_4, new SpriteSheetTexture("hit", 683, 1636, 54, 40));
            textureLocations.Add(OsuTexture.default_5, new SpriteSheetTexture("hit", 1026, 1412, 54, 40));
            textureLocations.Add(OsuTexture.default_6, new SpriteSheetTexture("hit", 1026, 1454, 54, 40));
            textureLocations.Add(OsuTexture.default_7, new SpriteSheetTexture("hit", 1082, 1412, 54, 40));
            textureLocations.Add(OsuTexture.default_8, new SpriteSheetTexture("hit", 1082, 1454, 54, 40));
            textureLocations.Add(OsuTexture.default_9, new SpriteSheetTexture("hit", 650, 1899, 54, 40));
            textureLocations.Add(OsuTexture.pausebutton, new SpriteSheetTexture("hit", 1844, 186, 48, 48));
            textureLocations.Add(OsuTexture.score_0, new SpriteSheetTexture("hit", 342, 1927, 42, 48));
            textureLocations.Add(OsuTexture.mouse_burst, new SpriteSheetTexture("hit", 1138, 1412, 38, 38));
            textureLocations.Add(OsuTexture.score_6, new SpriteSheetTexture("hit", 1138, 1452, 36, 48));
            textureLocations.Add(OsuTexture.score_8, new SpriteSheetTexture("hit", 1178, 1412, 36, 48));
            textureLocations.Add(OsuTexture.score_9, new SpriteSheetTexture("hit", 650, 1941, 36, 48));
            textureLocations.Add(OsuTexture.score_x, new SpriteSheetTexture("hit", 706, 1899, 36, 48));
            textureLocations.Add(OsuTexture.score_2, new SpriteSheetTexture("hit", 1958, 666, 34, 48));
            textureLocations.Add(OsuTexture.score_3, new SpriteSheetTexture("hit", 688, 1949, 34, 48));
            textureLocations.Add(OsuTexture.score_4, new SpriteSheetTexture("hit", 19 [...]

2021-08-20 06:37 UTC, peppy commented on osu!stream/Graphics/TextureManager_Load.cs
> +            }
```suggestion
            textureLocations.Clear();
            textureLocations.Add(OsuTexture.play_menu_background, new SpriteSheetTexture("hit", 0, 0, 1385, 210));
            textureLocations.Add(OsuTexture.spinner_background, new SpriteSheetTexture("hit", 0, 212, 1136, 640));
            textureLocations.Add(OsuTexture.cleared, new SpriteSheetTexture("hit", 0, 854, 1024, 654));
            textureLocations.Add(OsuTexture.scorebar_background, new SpriteSheetTexture("hit", 1138, 212, 704, 58));
            textureLocations.Add(OsuTexture.scorebar_colour, new SpriteSheetTexture("hit", 1387, 0, 646, 14));
            textureLocations.Add(OsuTexture.spinner_circle, new SpriteSheetTexture("hit", 1138, 272, 616, 616));
            textureLocations.Add(OsuTexture.countdown_background, new SpriteSheetTexture("hit", 0, 1510, 545, 203));
            textureLocations.Add(OsuTexture.spinner_clear, new SpriteSheetTexture("hit", 1387, 16, 510, 168));
            textureLocations.Add(OsuTexture.countdown_ready, new SpriteSheetTexture("hit", 0, 1715, 422, 90));
            textureLocations.Add(OsuTexture.failed, new SpriteSheetTexture("hit", 0, 1807, 388, 118));
            textureLocations.Add(OsuTexture.spinner_spin, new SpriteSheetTexture("hit", 1026, 890, 382, 170));
            textureLocations.Add(OsuTexture.demo, new SpriteSheetTexture("hit", 547, 1510, 350, 124));
            textureLocations.Add(OsuTexture.stream_changing_up, new SpriteSheetTexture("hit", 1026, 1062, 322, 194));
            textureLocations.Add(OsuTexture.stream_changing_down, new SpriteSheetTexture("hit", 424, 1715, 322, 182));
            textureLocations.Add(OsuTexture.play_menu_continue, new SpriteSheetTexture("hit", 1026, 1258, 316, 152));
            textureLocations.Add(OsuTexture.play_menu_quit, new SpriteSheetTexture("hit", 1410, 890, 316, 152));
            textureLocations.Add(OsuTexture.play_menu_restart, new SpriteSheetTexture("hit", 899, 1510, 316, 152));
            textureLocations.Add(OsuTexture.countdown_go, new SpriteSheetTexture("hit", 1350, 1062, 314, 144));
            textureLocations.Add(OsuTexture.sliderfollowcircle, new SpriteSheetTexture("hit", 1756, 272, 256, 256));
            textureLocations.Add(OsuTexture.stream_changing_arrow, new SpriteSheetTexture("hit", 1756, 530, 200, 266));
            textureLocations.Add(OsuTexture.hit300g, new SpriteSheetTexture("hit", 748, 1664, 190, 190));
            textureLocations.Add(OsuTexture.hit300k, new SpriteSheetTexture("hit", 1756, 798, 190, 190));
            textureLocations.Add(OsuTexture.hit300, new SpriteSheetTexture("hit", 1350, 1208, 188, 190));
            textureLocations.Add(OsuTexture.hit100, new SpriteSheetTexture("hit", 940, 1664, 180, 180));
            textureLocations.Add(OsuTexture.hit100k, new SpriteSheetTexture("hit", 1217, 1412, 180, 180));
            textureLocations.Add(OsuTexture.holdoverlay, new SpriteSheetTexture("hit", 748, 1856, 160, 160));
            textureLocations.Add(OsuTexture.countdown_2, new SpriteSheetTexture("hit", 1666, 1044, 158, 142));
            textureLocations.Add(OsuTexture.countdown_3, new SpriteSheetTexture("hit", 1540, 1208, 158, 138));
            textureLocations.Add(OsuTexture.hit0, new SpriteSheetTexture("hit", 910, 1856, 152, 148));
            textureLocations.Add(OsuTexture.hit50, new SpriteSheetTexture("hit", 1899, 16, 132, 132));
            textureLocations.Add(OsuTexture.tracks, new SpriteSheetTexture("hit", 1387, 186, 132, 16));
            textureLocations.Add(OsuTexture.hitcircle0, new SpriteSheetTexture("hit", 390, 1899, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle1, new SpriteSheetTexture("hit", 520, 1899, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle2, new SpriteSheetTexture("hit", 1122, 1664, 128, 128));
            textureLocations.Add(OsuTexture.hitcircle3, new SpriteSheetTexture("hit", 1399, 1400, 128, 128));
            textureLocations.Add(OsuTexture.holdactive, new SpriteSheetTexture("hit", 1899, 150, 118, 118));
            textureLocations.Add(OsuTexture.holdinactive, new SpriteSheetTexture("hit", 1826, 990, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_0, new SpriteSheetTexture("hit", 1540, 1348, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_1, new SpriteSheetTexture("hit", 1700, 1188, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_2, new SpriteSheetTexture("hit", 1122, 1794, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_3, new SpriteSheetTexture("hit", 1252, 1594, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_4, new SpriteSheetTexture("hit", 1399, 1530, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_5, new SpriteSheetTexture("hit", 1826, 1110, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_6, new SpriteSheetTexture("hit", 1252, 1714, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_7, new SpriteSheetTexture("hit", 1700, 1308, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_8, new SpriteSheetTexture("hit", 1529, 1468, 118, 118));
            textureLocations.Add(OsuTexture.sliderb_9, new SpriteSheetTexture("hit", 1064, 1914, 118, 118));
            textureLocations.Add(OsuTexture.sliderballoverlay, new SpriteSheetTexture("hit", 0, 1927, 118, 74));
            textureLocations.Add(OsuTexture.countdown_1, new SpriteSheetTexture("hit", 1958, 530, 86, 134));
            textureLocations.Add(OsuTexture.scorebar_marker_hit, new SpriteSheetTexture("hit", 120, 1927, 78, 78));
            textureLocations.Add(OsuTexture.sliderarrow, new SpriteSheetTexture("hit", 200, 1927, 78, 58));
            textureLocations.Add(OsuTexture.finger_outer, new SpriteSheetTexture("hit", 547, 1636, 74, 74));
            textureLocations.Add(OsuTexture.score_percent, new SpriteSheetTexture("hit", 280, 1927, 60, 48));
            textureLocations.Add(OsuTexture.finger_inner, new SpriteSheetTexture("hit", 623, 1636, 58, 58));
            textureLocations.Add(OsuTexture.default_0, new SpriteSheetTexture("hit", 200, 1987, 54, 40));
            textureLocations.Add(OsuTexture.default_2, new SpriteSheetTexture("hit", 256, 1987, 54, 40));
            textureLocations.Add(OsuTexture.default_3, new SpriteSheetTexture("hit", 312, 1977, 54, 40));
            textureLocations.Add(OsuTexture.default_4, new SpriteSheetTexture("hit", 683, 1636, 54, 40));
            textureLocations.Add(OsuTexture.default_5, new SpriteSheetTexture("hit", 1026, 1412, 54, 40));
            textureLocations.Add(OsuTexture.default_6, new SpriteSheetTexture("hit", 1026, 1454, 54, 40));
            textureLocations.Add(OsuTexture.default_7, new SpriteSheetTexture("hit", 1082, 1412, 54, 40));
            textureLocations.Add(OsuTexture.default_8, new SpriteSheetTexture("hit", 1082, 1454, 54, 40));
            textureLocations.Add(OsuTexture.default_9, new SpriteSheetTexture("hit", 650, 1899, 54, 40));
            textureLocations.Add(OsuTexture.pausebutton, new SpriteSheetTexture("hit", 1844, 186, 48, 48));
            textureLocations.Add(OsuTexture.score_0, new SpriteSheetTexture("hit", 342, 1927, 42, 48));
            textureLocations.Add(OsuTexture.mouse_burst, new SpriteSheetTexture("hit", 1138, 1412, 38, 38));
            textureLocations.Add(OsuTexture.score_6, new SpriteSheetTexture("hit", 1138, 1452, 36, 48));
            textureLocations.Add(OsuTexture.score_8, new SpriteSheetTexture("hit", 1178, 1412, 36, 48));
            textureLocations.Add(OsuTexture.score_9, new SpriteSheetTexture("hit", 650, 1941, 36, 48));
            textureLocations.Add(OsuTexture.score_x, new SpriteSheetTexture("hit", 706, 1899, 36, 48));
            textureLocations.Add(OsuTexture.score_2, new SpriteSheetTexture("hit", 1958, 666, 34, 48));
            textureLocations.Add(OsuTexture.score_3, new SpriteSheetTexture("hit", 688, 1949, 34, 48));
            textureLocations.Add(OsuTexture.score_4, new SpriteSheetTexture("hit", 19 [...]

2021-08-20 06:52 UTC, peppy commented
Just as a sanity check, have you confirmed that this still fixes the issue for you?

2021-08-20 06:52 UTC, Beyley commented
> Just as a sanity check, have you confirmed that this still fixes the issue for you?

Good catch, ill do that rn

2021-08-20 07:10 UTC, Beyley commented
> Just as a sanity check, have you confirmed that this still fixes the issue for you?

Can confirm it does work! tested it on my real device

2021-08-20 07:11 UTC, peppy approved these changes

2021-08-20 07:11 UTC, merged